_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/TRPO.py
        e:
            d42et9oy621wzw9pam078qdjh7tdjbji:
                args:
                    - --env-id
                    - HalfCheetah-v4
                    - --exp-name
                    - num_env_2
                    - --seed
                    - "1"
                    - --num-envs
                    - "2"
                    - --total-timesteps
                    - "1000000"
                    - --capture-video
                    - "True"
                    - --track
                    - "True"
                    - --wandb-project-name
                    - cleanRL
                    - --wandb-entity
                    - kieusontung8-hanoi-university-of-science-and-technology
                codePath: TRPO.py
                codePathLocal: TRPO.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "124142673920"
                        used: "104591351808"
                email: kieusontung8@gmail.com
                executable: /home/tung/miniforge3/envs/gym/bin/python
                git:
                    commit: 6bb7058d154b6b8e6e23f74963a053e008156145
                    remote: https://github.com/sontungkieu/practice-gymnasium.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-3498bf86-ab1e-f415-286e-ab37887ee2c0
                host: tung-Legion-Y540-15IRH-PG0
                memory:
                    total: "16676139008"
                os: Linux-6.14.0-24-generic-x86_64-with-glibc2.39
                program: /home/tung/practice-gymnasium/TRPO.py
                python: CPython 3.10.18
                root: /home/tung/practice-gymnasium
                startedAt: "2025-07-25T17:44:08.213199Z"
                writerId: d42et9oy621wzw9pam078qdjh7tdjbji
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
                - 35
            "4": 3.10.18
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
anneal_lr:
    value: true
batch_size:
    value: 4096
capture_video:
    value: true
clip_coef:
    value: 0.2
clip_vloss:
    value: true
cuda:
    value: true
env_id:
    value: HalfCheetah-v4
exp_name:
    value: num_env_2
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 1024
norm_adv:
    value: true
num_envs:
    value: 2
num_minibatches:
    value: 4
num_steps:
    value: 2048
seed:
    value: 1
target_kl:
    value: 0.01
torch_deterministic:
    value: true
total_timesteps:
    value: 1000000
track:
    value: true
update_epochs:
    value: 5
vf_coef:
    value: 0.5
wandb_entity:
    value: kieusontung8-hanoi-university-of-science-and-technology
wandb_project_name:
    value: cleanRL
